name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
    - name: Setup Node
      uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v2.2.0
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
